### ISSUE TITLE
Controller Verify SSL Breaks Availability Check with Valid Certs

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/pinakes#441]
### Issue
Check availability fails when controller URL is defined with an alternative port.

### Steps to Reproduce

1. Define:
```
PINAKES_CONTROLLER_URL=https://controller.example.org:443
PINAKES_CONTROLLER_VERIFY_SSL=true
```

2. Verify certificate on controller a good from the pinakes/catalog host:
```
curl https://controller.example.org:443 &> /dev/null && echo $?
0
```

### Expected Results
Platform in UI is available

### Observed Results
```
Mar 24 22:16:05 catalog.example.org bash[86689]: [2022-03-24 22:16:05,385] [87063] [ERROR] check_source_availability 140236529504512 Check availability failed on https://controller.example.org:443: expected str, bytes or os.PathLike object, not int
Mar 24 22:16:05 catalog.example.org bash[86689]: [2022-03-24 22:16:05,387] [87063] [ERROR] tasks 140236529504512 Source Automation Controller[https://controller.example.org:443] is unavailable, cannot refresh it
```

**Comment by Alex-Izquierdo** [comment]
@jamesmarshall24 This issue is related with https://issues.redhat.com/browse/SSP-2787
I don't think that it has relation with the port, but with the tls certificates. I suspect that if you disable the SSL verification, it will work. This error has been detected when the certificates could not be validated. The controller is using self-signed certificates and/or the CA is not installed on the pinakes node. Could you discard these scenarios?

**Comment by jamesmarshall24** [comment]
Hey @Alex-Izquierdo,

I assumed it was port because of `expected str, bytes or os.PathLike object, not int`. I'm using an internally managed CA to generate the cert and add the cacert to the system trust store. For example, curl requires no flag to bypass verification because its valid:

```
curl https://controller.example.org:443 &> /dev/null && echo $?
0
```

I will change the title of the issue to match. Maybe it is the same issue, but in this instance the certificate is valid on controller.
